// <auto-generated />
using LiturgieMakerAPI.LiturgieMaker.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace LiturgieMakerAPI.Migrations
{
    [DbContext(typeof(LiturgieMakerContext))]
    [Migration("20180309073001_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("LiturgieMakerAPI.Liedbundels.Model.Lied", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AantalVerzen");

                    b.Property<int>("LiedNummer");

                    b.Property<int?>("LiedbundelId");

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.HasIndex("LiedbundelId");

                    b.ToTable("Lied");
                });

            modelBuilder.Entity("LiturgieMakerAPI.Liedbundels.Model.Liedbundel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AantalLiederen");

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("Liedbundel");
                });

            modelBuilder.Entity("LiturgieMakerAPI.Liedbundels.Model.Vers", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("LiedId");

                    b.Property<string>("Tekst");

                    b.Property<int>("VersNummer");

                    b.HasKey("Id");

                    b.HasIndex("LiedId");

                    b.ToTable("Vers");
                });

            modelBuilder.Entity("LiturgieMakerAPI.LiturgieMaker.Model.Liturgie", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Aanvangsdatum");

                    b.Property<DateTime>("Publicatiedatum");

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.ToTable("Liturgie");
                });

            modelBuilder.Entity("LiturgieMakerAPI.LiturgieMaker.Model.LiturgieItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("Index");

                    b.Property<long?>("LiturgieId");

                    b.HasKey("Id");

                    b.HasIndex("LiturgieId");

                    b.ToTable("LiturgieItem");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LiturgieItem");
                });

            modelBuilder.Entity("LiturgieMakerAPI.LiturgieMaker.Model.LiturgieItems.LiedItem", b =>
                {
                    b.HasBaseType("LiturgieMakerAPI.LiturgieMaker.Model.LiturgieItem");

                    b.Property<long?>("LiedId");

                    b.HasIndex("LiedId");

                    b.ToTable("LiedItem");

                    b.HasDiscriminator().HasValue("LiedItem");
                });

            modelBuilder.Entity("LiturgieMakerAPI.LiturgieMaker.Model.LiturgieItems.SchriftlezingItem", b =>
                {
                    b.HasBaseType("LiturgieMakerAPI.LiturgieMaker.Model.LiturgieItem");

                    b.Property<int>("Hoofdstuk");

                    b.ToTable("SchriftlezingItem");

                    b.HasDiscriminator().HasValue("SchriftlezingItem");
                });

            modelBuilder.Entity("LiturgieMakerAPI.Liedbundels.Model.Lied", b =>
                {
                    b.HasOne("LiturgieMakerAPI.Liedbundels.Model.Liedbundel", "Liedbundel")
                        .WithMany("Liederen")
                        .HasForeignKey("LiedbundelId");
                });

            modelBuilder.Entity("LiturgieMakerAPI.Liedbundels.Model.Vers", b =>
                {
                    b.HasOne("LiturgieMakerAPI.Liedbundels.Model.Lied", "Lied")
                        .WithMany("Verzen")
                        .HasForeignKey("LiedId");
                });

            modelBuilder.Entity("LiturgieMakerAPI.LiturgieMaker.Model.LiturgieItem", b =>
                {
                    b.HasOne("LiturgieMakerAPI.LiturgieMaker.Model.Liturgie", "Liturgie")
                        .WithMany("Items")
                        .HasForeignKey("LiturgieId");
                });

            modelBuilder.Entity("LiturgieMakerAPI.LiturgieMaker.Model.LiturgieItems.LiedItem", b =>
                {
                    b.HasOne("LiturgieMakerAPI.Liedbundels.Model.Lied", "Lied")
                        .WithMany()
                        .HasForeignKey("LiedId");
                });
#pragma warning restore 612, 618
        }
    }
}
